name: Webapp lint

on:
  push:
    paths:
      - 'src/**'
      - 'biome.json'
      - 'package.json'
      - 'next.config.ts'
      - 'tsconfig.json'
      - 'postcss.config.mjs'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'biome.json'
      - 'package.json'
      - 'next.config.ts'
      - 'tsconfig.json'
      - 'postcss.config.mjs'

jobs:
  lint:
    name: Biome Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm -s lint
